package cnam.teleconsult.modele.bean;
// Generated 12 août 2016 14:40:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContributeurId generated by hbm2java
 */
@Embeddable
public class ContributeurId implements java.io.Serializable {

	private int dmpcsubmissionId;
	private int personnelsanteId;

	public ContributeurId() {
	}

	public ContributeurId(int dmpcsubmissionId, int personnelsanteId) {
		this.dmpcsubmissionId = dmpcsubmissionId;
		this.personnelsanteId = personnelsanteId;
	}

	@Column(name = "DMPCSUBMISSION_ID", nullable = false)
	public int getDmpcsubmissionId() {
		return this.dmpcsubmissionId;
	}

	public void setDmpcsubmissionId(int dmpcsubmissionId) {
		this.dmpcsubmissionId = dmpcsubmissionId;
	}

	@Column(name = "PERSONNELSANTE_ID", nullable = false)
	public int getPersonnelsanteId() {
		return this.personnelsanteId;
	}

	public void setPersonnelsanteId(int personnelsanteId) {
		this.personnelsanteId = personnelsanteId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContributeurId))
			return false;
		ContributeurId castOther = (ContributeurId) other;

		return (this.getDmpcsubmissionId() == castOther.getDmpcsubmissionId())
				&& (this.getPersonnelsanteId() == castOther.getPersonnelsanteId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDmpcsubmissionId();
		result = 37 * result + this.getPersonnelsanteId();
		return result;
	}

}
