package cnam.teleconsult.modele.bean;
// Generated 12 août 2016 14:40:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contributeur generated by hbm2java
 */
@Entity
@Table(name = "contributeur", catalog = "teleconsult")
public class Contributeur implements java.io.Serializable {

	private ContributeurId id;
	private Avis avis;
	private Dmpcpersonnelsante dmpcpersonnelsante;
	private String tempsPasse;

	public Contributeur() {
	}

	public Contributeur(ContributeurId id, Avis avis, Dmpcpersonnelsante dmpcpersonnelsante, String tempsPasse) {
		this.id = id;
		this.avis = avis;
		this.dmpcpersonnelsante = dmpcpersonnelsante;
		this.tempsPasse = tempsPasse;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dmpcsubmissionId", column = @Column(name = "DMPCSUBMISSION_ID", nullable = false)),
			@AttributeOverride(name = "personnelsanteId", column = @Column(name = "PERSONNELSANTE_ID", nullable = false)) })
	public ContributeurId getId() {
		return this.id;
	}

	public void setId(ContributeurId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMPCSUBMISSION_ID", nullable = false, insertable = false, updatable = false)
	public Avis getAvis() {
		return this.avis;
	}

	public void setAvis(Avis avis) {
		this.avis = avis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSONNELSANTE_ID", nullable = false, insertable = false, updatable = false)
	public Dmpcpersonnelsante getDmpcpersonnelsante() {
		return this.dmpcpersonnelsante;
	}

	public void setDmpcpersonnelsante(Dmpcpersonnelsante dmpcpersonnelsante) {
		this.dmpcpersonnelsante = dmpcpersonnelsante;
	}

	@Column(name = "TEMPS_PASSE", nullable = false, length = 20)
	public String getTempsPasse() {
		return this.tempsPasse;
	}

	public void setTempsPasse(String tempsPasse) {
		this.tempsPasse = tempsPasse;
	}

}
