package cnam.teleconsult.modele.bean;
// Generated 3 sept. 2016 15:21:31 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dmpcpersonnelsante generated by hbm2java
 */
@Entity
@Table(name = "dmpcpersonnelsante", catalog = "teleconsult")
public class Dmpcpersonnelsante implements java.io.Serializable {

	private Integer personnelsanteId;
	private Specialite specialite;
	private String personnelsanteNom;
	private String personnelsantePrenom;
	private String personnelsanteMdp;
	private String personnelsanteEmail;
	private String personnelsanteAdeli;
	private String personnelsanteRpps;
	private String personnelsanteRole;
	private String personnelsanteSecteuractivite;
	private String personnelsanteTelephone;
	private Set<Dmpcstructuresante> dmpcstructuresantes = new HashSet<Dmpcstructuresante>(0);
	private Set<Examen> examens = new HashSet<Examen>(0);
	private Set<Dmpcpatient> dmpcpatients = new HashSet<Dmpcpatient>(0);
	private Set<Consultation> consultations = new HashSet<Consultation>(0);
	private Set<Dmpcstructuresante> dmpcstructuresantes_1 = new HashSet<Dmpcstructuresante>(0);
	private Set<Contributeur> contributeurs = new HashSet<Contributeur>(0);

	public Dmpcpersonnelsante() {
	}

	public Dmpcpersonnelsante(String personnelsanteNom, String personnelsantePrenom, String personnelsanteMdp,
			String personnelsanteEmail) {
		this.personnelsanteNom = personnelsanteNom;
		this.personnelsantePrenom = personnelsantePrenom;
		this.personnelsanteMdp = personnelsanteMdp;
		this.personnelsanteEmail = personnelsanteEmail;
	}

	public Dmpcpersonnelsante(Specialite specialite, String personnelsanteNom, String personnelsantePrenom,
			String personnelsanteMdp, String personnelsanteEmail, String personnelsanteAdeli, String personnelsanteRpps,
			String personnelsanteRole, String personnelsanteSecteuractivite, String personnelsanteTelephone,
			Set<Dmpcstructuresante> dmpcstructuresantes, Set<Examen> examens, Set<Dmpcpatient> dmpcpatients,
			Set<Consultation> consultations, Set<Dmpcstructuresante> dmpcstructuresantes_1,
			Set<Contributeur> contributeurs) {
		this.specialite = specialite;
		this.personnelsanteNom = personnelsanteNom;
		this.personnelsantePrenom = personnelsantePrenom;
		this.personnelsanteMdp = personnelsanteMdp;
		this.personnelsanteEmail = personnelsanteEmail;
		this.personnelsanteAdeli = personnelsanteAdeli;
		this.personnelsanteRpps = personnelsanteRpps;
		this.personnelsanteRole = personnelsanteRole;
		this.personnelsanteSecteuractivite = personnelsanteSecteuractivite;
		this.personnelsanteTelephone = personnelsanteTelephone;
		this.dmpcstructuresantes = dmpcstructuresantes;
		this.examens = examens;
		this.dmpcpatients = dmpcpatients;
		this.consultations = consultations;
		this.dmpcstructuresantes_1 = dmpcstructuresantes_1;
		this.contributeurs = contributeurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PERSONNELSANTE_ID", unique = true, nullable = false)
	public Integer getPersonnelsanteId() {
		return this.personnelsanteId;
	}

	public void setPersonnelsanteId(Integer personnelsanteId) {
		this.personnelsanteId = personnelsanteId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SPECIALITE_ID")
	public Specialite getSpecialite() {
		return this.specialite;
	}

	public void setSpecialite(Specialite specialite) {
		this.specialite = specialite;
	}

	@Column(name = "PERSONNELSANTE_NOM", nullable = false, length = 20)
	public String getPersonnelsanteNom() {
		return this.personnelsanteNom;
	}

	public void setPersonnelsanteNom(String personnelsanteNom) {
		this.personnelsanteNom = personnelsanteNom;
	}

	@Column(name = "PERSONNELSANTE_PRENOM", nullable = false, length = 20)
	public String getPersonnelsantePrenom() {
		return this.personnelsantePrenom;
	}

	public void setPersonnelsantePrenom(String personnelsantePrenom) {
		this.personnelsantePrenom = personnelsantePrenom;
	}

	@Column(name = "PERSONNELSANTE_MDP", nullable = false, length = 20)
	public String getPersonnelsanteMdp() {
		return this.personnelsanteMdp;
	}

	public void setPersonnelsanteMdp(String personnelsanteMdp) {
		this.personnelsanteMdp = personnelsanteMdp;
	}

	@Column(name = "PERSONNELSANTE_EMAIL", nullable = false, length = 200)
	public String getPersonnelsanteEmail() {
		return this.personnelsanteEmail;
	}

	public void setPersonnelsanteEmail(String personnelsanteEmail) {
		this.personnelsanteEmail = personnelsanteEmail;
	}

	@Column(name = "PERSONNELSANTE_ADELI", length = 20)
	public String getPersonnelsanteAdeli() {
		return this.personnelsanteAdeli;
	}

	public void setPersonnelsanteAdeli(String personnelsanteAdeli) {
		this.personnelsanteAdeli = personnelsanteAdeli;
	}

	@Column(name = "PERSONNELSANTE_RPPS", length = 20)
	public String getPersonnelsanteRpps() {
		return this.personnelsanteRpps;
	}

	public void setPersonnelsanteRpps(String personnelsanteRpps) {
		this.personnelsanteRpps = personnelsanteRpps;
	}

	@Column(name = "PERSONNELSANTE_ROLE", length = 20)
	public String getPersonnelsanteRole() {
		return this.personnelsanteRole;
	}

	public void setPersonnelsanteRole(String personnelsanteRole) {
		this.personnelsanteRole = personnelsanteRole;
	}

	@Column(name = "PERSONNELSANTE_SECTEURACTIVITE", length = 20)
	public String getPersonnelsanteSecteuractivite() {
		return this.personnelsanteSecteuractivite;
	}

	public void setPersonnelsanteSecteuractivite(String personnelsanteSecteuractivite) {
		this.personnelsanteSecteuractivite = personnelsanteSecteuractivite;
	}

	@Column(name = "PERSONNELSANTE_TELEPHONE", length = 20)
	public String getPersonnelsanteTelephone() {
		return this.personnelsanteTelephone;
	}

	public void setPersonnelsanteTelephone(String personnelsanteTelephone) {
		this.personnelsanteTelephone = personnelsanteTelephone;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "dmpcpersonnelsantes")
	public Set<Dmpcstructuresante> getDmpcstructuresantes() {
		return this.dmpcstructuresantes;
	}

	public void setDmpcstructuresantes(Set<Dmpcstructuresante> dmpcstructuresantes) {
		this.dmpcstructuresantes = dmpcstructuresantes;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "dmpcpersonnelsante")
	public Set<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(Set<Examen> examens) {
		this.examens = examens;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "dmpcpersonnelsante")
	public Set<Dmpcpatient> getDmpcpatients() {
		return this.dmpcpatients;
	}

	public void setDmpcpatients(Set<Dmpcpatient> dmpcpatients) {
		this.dmpcpatients = dmpcpatients;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "dmpcpersonnelsante")
	public Set<Consultation> getConsultations() {
		return this.consultations;
	}

	public void setConsultations(Set<Consultation> consultations) {
		this.consultations = consultations;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "dmpcpersonnelsantes")
	public Set<Dmpcstructuresante> getDmpcstructuresantes_1() {
		return this.dmpcstructuresantes_1;
	}

	public void setDmpcstructuresantes_1(Set<Dmpcstructuresante> dmpcstructuresantes_1) {
		this.dmpcstructuresantes_1 = dmpcstructuresantes_1;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "dmpcpersonnelsante")
	public Set<Contributeur> getContributeurs() {
		return this.contributeurs;
	}

	public void setContributeurs(Set<Contributeur> contributeurs) {
		this.contributeurs = contributeurs;
	}

}
