package cnam.teleconsult.modele.bean;
// Generated 24 août 2016 08:19:15 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resultat generated by hbm2java
 */
@Entity
@Table(name = "resultat", catalog = "teleconsult")
public class Resultat implements java.io.Serializable {

	private Integer dmpcdocumentId;
	private Consultation consultation;
	private Examen examen;
	private String imageNom;
	private String imagePath;

	public Resultat() {
	}

	public Resultat(Consultation consultation, Examen examen, String imageNom, String imagePath) {
		this.consultation = consultation;
		this.examen = examen;
		this.imageNom = imageNom;
		this.imagePath = imagePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DMPCDOCUMENT_ID", unique = true, nullable = false)
	public Integer getDmpcdocumentId() {
		return this.dmpcdocumentId;
	}

	public void setDmpcdocumentId(Integer dmpcdocumentId) {
		this.dmpcdocumentId = dmpcdocumentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CONSULTATION_ID", nullable = false)
	public Consultation getConsultation() {
		return this.consultation;
	}

	public void setConsultation(Consultation consultation) {
		this.consultation = consultation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EXAMEN_ID", nullable = false)
	public Examen getExamen() {
		return this.examen;
	}

	public void setExamen(Examen examen) {
		this.examen = examen;
	}

	@Column(name = "IMAGE_NOM", nullable = false, length = 100)
	public String getImageNom() {
		return this.imageNom;
	}

	public void setImageNom(String imageNom) {
		this.imageNom = imageNom;
	}

	@Column(name = "IMAGE_PATH", nullable = false, length = 100)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

}
