package cnam.teleconsult.modele.bean;
// Generated 3 sept. 2016 15:21:31 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Specialite generated by hbm2java
 */
@Entity
@Table(name = "specialite", catalog = "teleconsult")
public class Specialite implements java.io.Serializable {

	private Integer specialiteId;
	private String specialiteNom;
	private Set<Dmpcpersonnelsante> dmpcpersonnelsantes = new HashSet<Dmpcpersonnelsante>(0);

	public Specialite() {
	}

	public Specialite(String specialiteNom) {
		this.specialiteNom = specialiteNom;
	}

	public Specialite(String specialiteNom, Set<Dmpcpersonnelsante> dmpcpersonnelsantes) {
		this.specialiteNom = specialiteNom;
		this.dmpcpersonnelsantes = dmpcpersonnelsantes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SPECIALITE_ID", unique = true, nullable = false)
	public Integer getSpecialiteId() {
		return this.specialiteId;
	}

	public void setSpecialiteId(Integer specialiteId) {
		this.specialiteId = specialiteId;
	}

	@Column(name = "SPECIALITE_NOM", nullable = false, length = 200)
	public String getSpecialiteNom() {
		return this.specialiteNom;
	}

	public void setSpecialiteNom(String specialiteNom) {
		this.specialiteNom = specialiteNom;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "specialite")
	public Set<Dmpcpersonnelsante> getDmpcpersonnelsantes() {
		return this.dmpcpersonnelsantes;
	}

	public void setDmpcpersonnelsantes(Set<Dmpcpersonnelsante> dmpcpersonnelsantes) {
		this.dmpcpersonnelsantes = dmpcpersonnelsantes;
	}

}
